name: Build
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build the project according to the steps
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install rust nightly
        run: |
          rustup override set nightly

      - name: Configure rust target
        run: |
          rustup target add thumbv7em-none-eabihf

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run steps
        run: |
          ./ci.sh
